### ISSUE TITLE
Default revive rules are not enabled due to custom enablement of 2 revive rules

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#11033]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
While trying to vendor gardener/gardener@v1.110.0 into the registry-cache extension, golangci-lint reported:
```
pkg/admission/validator/mirror/shoot.go:37:45: redefines-builtin-id: redefinition of the built-in function new (revive)
func (s *shoot) Validate(_ context.Context, new, _ client.Object) error {
                                            ^
pkg/admission/validator/cache/shoot.go:42:47: redefines-builtin-id: redefinition of the built-in function new (revive)
func (s *shoot) Validate(ctx context.Context, new, old client.Object) error {
                                              ^
pkg/webhook/mirror/ensurer.go:42:85: redefines-builtin-id: redefinition of the built-in function new (revive)
func (e *ensurer) EnsureCRIConfig(ctx context.Context, gctx gcontext.GardenContext, new, _ *extensionsv1alpha1.CRIConfig) error {
```

After investigation I saw that gardener/gardener is also affected by the same findings. 

<details>

```
pkg/utils/validation/validation.go:10:32: redefines-builtin-id: redefinition of the built-in function new (revive)
func ShouldEnforceImmutability(new, old []string) bool {
                               ^
pkg/utils/validation/validation.go:23:12: redefines-builtin-id: redefinition of the built-in function new (revive)
func equal(new, old []string) bool {
           ^
pkg/utils/random.go:28:2: redefines-builtin-id: redefinition of the built-in function max (revive)
	max := new(big.Int).SetInt64(int64(len(allowedCharacters)))
	^
pkg/utils/random.go:42:21: redefines-builtin-id: redefinition of the built-in function max (revive)
func RandomDuration(max time.Duration) time.Duration {
                    ^
pkg/utils/random.go:51:37: redefines-builtin-id: redefinition of the built-in function max (revive)
func RandomDurationWithMetaDuration(max *metav1.Duration) time.Duration {
                                    ^
pkg/apis/authentication/validation/validation.go:23:2: redefines-builtin-id: redefinition of the built-in function min (revive)
	const min = 10 * time.Minute
	^
pkg/apis/settings/validation/cluster_openidconnect_preset.go:25:47: redefines-builtin-id: redefinition of the built-in function new (revive)
func ValidateClusterOpenIDConnectPresetUpdate(new, old *settings.ClusterOpenIDConnectPreset) field.ErrorList {
                                              ^
pkg/apis/core/v1beta1/helper/helper.go:1620:2: redefines-builtin-id: redefinition of the built-in function copy (revive)
	copy := left.DeepCopy()
	^
pkg/controller/service/reconciler.go:182:5: redefines-builtin-id: redefinition of the built-in function min (revive)
				var (
					min, max    = 30000, 32767
					newNodePort = int32(rand.N(max-min) + min) // #nosec: G115 G404 -- Value range limited in previous line, no cryptographic context.
				)
pkg/scheduler/controller/shoot/reconciler.go:368:2: redefines-builtin-id: redefinition of the built-in function min (revive)
	var (
		bestCandidate gardencorev1beta1.Seed
		min           *int
		seedUsage     = v1beta1helper.CalculateSeedUsage(shootList)
	)
pkg/controllermanager/controller/shoot/maintenance/reconciler.go:633:177: redefines-builtin-id: redefinition of the built-in type error (revive)
func shouldKubernetesVersionBeUpdated(kubernetesVersion string, autoUpdate bool, profile *gardencorev1beta1.CloudProfile) (shouldBeUpdated bool, reason string, isExpired bool, error error) {
                                                                                                                                                                                ^
extensions/pkg/webhook/registration_test.go:62:5: redefines-builtin-id: redefinition of the built-in function copy (revive)
				copy := configs.DeepCopy()
				^
```

</details>

However, after diffing `.golangci.yaml` files I see that for gardener/gardener there is a custom revive linter configuration: https://github.com/gardener/gardener/blob/26d505bd67ad85b126c595827edeb56cf8df3eee/.golangci.yaml.in#L58-L65

The configuration makes revive to enable only these 6 rules. All the [default revive rules](https://github.com/mgechev/revive/blob/78c3a6c363edb5757ca829c9befa25bf75ac8bfc/config/config.go#L16-L40) are not enabled (`redefines-builtin-id` is part of them).

Introduced with #8503.

From https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/.golangci.yaml.in#L58-L65, only 2 linters are not enabled by default: duplicated-imports and early-return.

**What you expected to happen**:
The default revive rules to be enabled.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.110.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
