### PR TITLE
Enable default revive rules with a golangci-lint linter (revive)

### LINKED ISSUE #11033: Default revive rules are not enabled due to custom enablement of 2 revive rules
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
While trying to vendor gardener/gardener@v1.110.0 into the registry-cache extension, golangci-lint reported:
```
pkg/admission/validator/mirror/shoot.go:37:45: redefines-builtin-id: redefinition of the built-in function new (revive)
func (s *shoot) Validate(_ context.Context, new, _ client.Object) error {
                                            ^
pkg/admission/validator/cache/shoot.go:42:47: redefines-builtin-id: redefinition of the built-in function new (revive)
func (s *shoot) Validate(ctx context.Context, new, old client.Object) error {
                                              ^
pkg/webhook/mirror/ensurer.go:42:85: redefines-builtin-id: redefinition of the built-in function new (revive)
func (e *ensurer) EnsureCRIConfig(ctx context.Context, gctx gcontext.GardenContext, new, _ *extensionsv1alpha1.CRIConfig) error {
```

After investigation I saw that gardener/gardener is also affected by the same findings. 

<details>

```
pkg/utils/validation/validation.go:10:32: redefines-builtin-id: redefinition of the built-in function new (revive)
func ShouldEnforceImmutability(new, old []string) bool {
                               ^
pkg/utils/validation/validation.go:23:12: redefines-builtin-id: redefinition of the built-in function new (revive)
func equal(new, old []string) bool {
           ^
pkg/utils/random.go:28:2: redefines-builtin-id: redefinition of the built-in function max (revive)
	max := new(big.Int).SetInt64(int64(len(allowedCharacters)))
	^
pkg/utils/random.go:42:21: redefines-builtin-id: redefinition of the built-in function max (revive)
func RandomDuration(max time.Duration) time.Duration {
                    ^
pkg/utils/random.go:51:37: redefines-builtin-id: redefinition of the built-in function max (revive)
func RandomDurationWithMetaDuration(max *metav1.Duration) time.Duration {
                                    ^
pkg/apis/authentication/validation/validation.go:23:2: redefines-builtin-id: redefinition of the built-in function min (revive)
	const min = 10 * time.Minute
	^
pkg/apis/settings/validation/cluster_openidconnect_preset.go:25:47: redefines-builtin-id: redefinition of the built-in function new (revive)
func ValidateClusterOpenIDConnectPresetUpdate(new, old *settings.ClusterOpenIDConnectPreset) field.ErrorList {
                                              ^
pkg/apis/core/v1beta1/helper/helper.go:1620:2: redefines-builtin-id: redefinition of the built-in function copy (revive)
	copy := left.DeepCopy()
	^
pkg/controller/service/reconciler.go:182:5: redefines-builtin-id: redefinition of the built-in function min (revive)
				var (
					min, max    = 30000, 32767
					newNodePort = int32(rand.N(max-min) + min) // #nosec: G115 G404 -- Value range limited in previous line, no cryptographic context.
				)
pkg/scheduler/controller/shoot/reconciler.go:368:2: redefines-builtin-id: redefinition of the built-in function min (revive)
	var (
		bestCandidate gardencorev1beta1.Seed
		min           *int
		seedUsage     = v1beta1helper.CalculateSeedUsage(shootList)
	)
pkg/controllermanager/controller/shoot/maintenance/reconciler.go:633:177: redefines-builtin-id: redefinition of the built-in type error (revive)
func shouldKubernetesVersionBeUpdated(kubernetesVersion string, autoUpdate bool, profile *gardencorev1beta1.CloudProfile) (shouldBeUpdated bool, reason string, isExpired bool, error error) {
                                                                                                                                                                                ^
extensions/pkg/webhook/registration_test.go:62:5: redefines-builtin-id: redefinition of the built-in function copy (revive)
				copy := configs.DeepCopy()
				^
```

</details>

However, after diffing `.golangci.yaml` files I see that for gardener/gardener there is a custom revive linter configuration: https://github.com/gardener/gardener/blob/26d505bd67ad85b126c595827edeb56cf8df3eee/.golangci.yaml.in#L58-L65

The configuration makes revive to enable only these 6 rules. All the [default revive rules](https://github.com/mgechev/revive/blob/78c3a6c363edb5757ca829c9befa25bf75ac8bfc/config/config.go#L16-L40) are not enabled (`redefines-builtin-id` is part of them).

Introduced with #8503.

From https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/.golangci.yaml.in#L58-L65, only 2 linters are not enabled by default: duplicated-imports and early-return.

**What you expected to happen**:
The default revive rules to be enabled.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.110.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by DobromirNPeev**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Enables default revive linter rules by adding enable-default-rules: true to the revive configuration in .golangci.yaml.in. Previously, explicitly listing rules under rules: inadvertently disabled all default revive rules, causing violations to go undetected. This PR also fixes all resulting violations across the codebase.

**Which issue(s) this PR fixes**:
Fixes #11033

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
/lgtm

**Review by RadaBDimitrova — COMMENTED** [review]
Good job fixing the linter issues, the blank-imports one is tricky!
/lgtm

File: extensions/pkg/webhook/controlplane/genericmutator/mutator.go [hunk 1]
```diff
@@ -37,61 +37,61 @@ import (
 type Ensurer interface {
 	// EnsureKubeAPIServerDeployment ensures that the kube-apiserver deployment conforms to the provider requirements.
 	// "old" might be "nil" and must always be checked.
```
Comment (ialidzhikov) [inline extensions/pkg/webhook/controlplane/genericmutator/mutator.go]: Doc strings need update.

```suggestion
	// "oldDeployment" might be "nil" and must always be checked.
```

The same comment applies to all of the occurrences in this file.

File: pkg/api/core/validation/project_test.go [hunk 2]
```diff
@@ -625,10 +625,10 @@ var _ = Describe("Project Validation Tests", func() {
 		})
 
 		DescribeTable("namespace immutability",
-			func(old, new *string, matcher gomegatypes.GomegaMatcher) {
-				project.Spec.Namespace = old
+			func(oldVal, newVal *string, matcher gomegatypes.GomegaMatcher) {
```
Comment (ialidzhikov) [inline pkg/api/core/validation/project_test.go]:
```suggestion
			func(oldValue, newValue *string, matcher gomegatypes.GomegaMatcher) {
```

or

```suggestion
			func(oldNamespace, newNamespace *string, matcher gomegatypes.GomegaMatcher) {
```

File: pkg/gardenlet/bootstrap/certificate/certificate_util.go [hunk 3]
```diff
@@ -47,11 +47,11 @@ func nextRotationDeadline(certificate tls.Certificate, validityConfig *gardenlet
 // try to rotate certificates at the same time for the rest of the lifetime
 func jitteryDuration(totalDuration float64, minPercentage, maxPercentage *int32) time.Duration {
 	var (
-		min = ptr.Deref(minPercentage, 70)
-		max = ptr.Deref(maxPercentage, 90)
+		minPercentageVal = ptr.Deref(minPercentage, 70)
+		maxPercentageVal = ptr.Deref(maxPercentage, 90)
```
Comment (ialidzhikov) [inline pkg/gardenlet/bootstrap/certificate/certificate_util.go]:
```suggestion
		minPercentageValue = ptr.Deref(minPercentage, 70)
		maxPercentageValue = ptr.Deref(maxPercentage, 90)
```

File: pkg/component/shared/victorialogs.go [hunk 4]
```diff
@@ -5,7 +5,7 @@
 package shared
 
 import (
-	_ "crypto/sha256"
+	_ "crypto/sha256" // for SHA-256 hash registration
```
Comment (ialidzhikov) [inline pkg/component/shared/victorialogs.go]: We could be more concrete about why it is needed and how it is used.

```suggestion
	_ "crypto/sha256" // registers SHA-256 with crypto.RegisterHash so github.com/opencontainers/go-digest can parse sha256 digests in SplitImageRef
```

We could place it in the line above if no linter complains about it:
```suggestion
	// Registers SHA-256 with crypto.RegisterHash so github.com/opencontainers/go-digest can parse sha256 digests in SplitImageRef
	_ "crypto/sha256"
```

File: pkg/component/autoscaling/pvcautoscaler/assets/doc.go [hunk 5]
```diff
@@ -7,6 +7,5 @@
 package assets
 
 import (
-	// Import to register the types for CRD generation.
-	_ "github.com/gardener/pvc-autoscaler/api/autoscaling/v1alpha1"
```
Comment (ialidzhikov) [inline pkg/component/autoscaling/pvcautoscaler/assets/doc.go:10]: I prefer the previous revision. Can we use `// Import to register the types for CRD generation.` everywhere where we have such blank imports for CRD generation.

**Review by ialidzhikov — COMMENTED** [review]
Very elegant solution with the new `enable-default-rules: true` option of the `revive` linter.
Back in the days when I opened the corresponding issue, I think there was no such configuration option.

Minor suggestions, otherwise lgtm.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]

**Comment by ialidzhikov** [comment]
/hold
to unblock tide for the PRs that need to be cherry-picked to the `release-v1.148` branch
I will unhold afterwards.
