### PR TITLE
Fix broken master

### PR DESCRIPTION
**Pull request by timebertt**
Master is broken after merging https://github.com/gardener/gardener/pull/4963 and https://github.com/gardener/gardener/pull/4883 concurrently.

From https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/227#L617989ee:195:
```
> Check
Executing golangci-lint
pkg/gardenlet/controller/shoot/shoot_control_migrate.go:58:151: too many arguments in call to r.patchShootStatusOperationError (typecheck)
			updateErr := r.patchShootStatusOperationError(ctx, gardenClient.Client(), nil, shoot, syncErr.Error(), gardencorev1beta1.LastOperationTypeMigrate, shoot.Status.LastErrors...)
			                                                                                                                                                   ^
make: *** [Makefile:186: check] Error 1
```

cc @vpnachev @plkokanov

### CODE REVIEW

**Review by krgostev — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
